# Generated by Django 4.0.4 on 2022-05-01 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Remedio',
            fields=[
                ('id', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('stock', models.IntegerField(max_length=9)),
            ],
        ),
    ]
