# Generated by Django 4.0.4 on 2022-05-01 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaCesfam', '0002_alter_remedio_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('contra', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
    ]
