# Generated by Django 4.0.4 on 2022-05-02 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaCesfam', '0003_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meds_Entregados',
            fields=[
                ('id', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('receta_id', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('rut', models.IntegerField()),
                ('digitoVer', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('celular', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('fecha', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Remedio',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
