# Generated by Django 4.0.4 on 2022-05-02 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaCesfam', '0004_meds_entregados_paciente_receta_delete_remedio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=500)),
                ('stock', models.IntegerField()),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('rut', models.IntegerField()),
                ('digitoVer', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=50)),
                ('contra', models.CharField(max_length=50)),
                ('tipoUsuario', models.CharField(max_length=50)),
            ],
        ),
    ]
